from agent.agent import create_agent
from html import escape


def _extract_text(content):
        if isinstance(content, str):
                return content

        if isinstance(content, list):
                text_parts = []
                for block in content:
                        if isinstance(block, dict) and block.get("type") == "text":
                                text_parts.append(block.get("text", ""))
                if text_parts:
                        return "\n\n".join(part for part in text_parts if part)

        return str(content)


def _markdownish_to_html(text):
        lines = text.splitlines()
        html_parts = []
        in_list = False

        for raw_line in lines:
                line = raw_line.strip()

                if not line:
                        if in_list:
                                html_parts.append("</ul>")
                                in_list = False
                        continue

                if line.startswith("# "):
                        if in_list:
                                html_parts.append("</ul>")
                                in_list = False
                        html_parts.append(f"<h1>{escape(line[2:].strip())}</h1>")
                        continue

                if line.startswith("## "):
                        if in_list:
                                html_parts.append("</ul>")
                                in_list = False
                        html_parts.append(f"<h2>{escape(line[3:].strip())}</h2>")
                        continue

                if line.startswith("- ") or line.startswith("* "):
                        if not in_list:
                                html_parts.append("<ul>")
                                in_list = True
                        html_parts.append(f"<li>{escape(line[2:].strip())}</li>")
                        continue

                if in_list:
                        html_parts.append("</ul>")
                        in_list = False

                html_parts.append(f"<p>{escape(line)}</p>")

        if in_list:
                html_parts.append("</ul>")

        return "\n".join(html_parts)


def _render_report_html(report_text):
        content_html = _markdownish_to_html(report_text)
        return f"""<!doctype html>
<html lang=\"en\">
<head>
    <meta charset=\"utf-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
    <title>Investment Memo</title>
    <style>
        :root {{
            --bg: #f7f8fc;
            --panel: #ffffff;
            --text: #1c2430;
            --muted: #5a6677;
            --accent: #0b6bcb;
            --border: #dbe3ef;
        }}
        * {{ box-sizing: border-box; }}
        body {{
            margin: 0;
            font-family: Segoe UI, -apple-system, BlinkMacSystemFont, sans-serif;
            color: var(--text);
            background: radial-gradient(circle at top right, #dceeff 0%, var(--bg) 55%);
            line-height: 1.6;
        }}
        .wrap {{
            max-width: 900px;
            margin: 40px auto;
            padding: 0 16px;
        }}
        .card {{
            background: var(--panel);
            border: 1px solid var(--border);
            border-radius: 16px;
            box-shadow: 0 10px 30px rgba(8, 24, 44, 0.08);
            padding: 28px;
        }}
        h1 {{
            margin: 0 0 18px;
            font-size: 1.8rem;
            color: var(--accent);
        }}
        h2 {{
            margin: 22px 0 10px;
            font-size: 1.2rem;
            color: #0e2f55;
            border-bottom: 1px solid var(--border);
            padding-bottom: 6px;
        }}
        p {{ margin: 10px 0; color: var(--muted); }}
        ul {{ margin: 8px 0 12px 22px; }}
        li {{ margin: 6px 0; }}
        .foot {{ margin-top: 20px; font-size: 0.9rem; color: #74839a; }}
    </style>
</head>
<body>
    <main class=\"wrap\">
        <section class=\"card\">
            {content_html}
            <div class=\"foot\">Generated by Market Researcher</div>
        </section>
    </main>
</body>
</html>
"""

def run():
    agent = create_agent()

    company = input("Enter company name: ")

    result = agent.invoke({
        "messages": [("user", company)]
    })

    final_answer = result["messages"][-1].content
    report_text = _extract_text(final_answer)
    print("\n\n", report_text)

    html_report = _render_report_html(report_text)
    with open("report.html", "w", encoding="utf-8") as f:
        f.write(html_report)

    print("\nSaved HTML report to: report.html")


if __name__ == "__main__":
    run()